### ISSUE TITLE
The log created time does not reflect timezone

### ISSUE THREAD

**Issue by fukuchi** [Daniel-KM/Omeka-S-module-Log#3]
In the job browse.phtml overwritten by the Log module, the job started time is displayed reflecting timezone by calling i18n()->dateFormat(). On the other hand, the created time of logs are not reflecting the timezone shown in the admin/log/browse.phtml. I want to see the date/time of both jobs and logs in the same format.

How about to modify them like the following?

>             <td><?= $this->i18n()->dateFormat($log->created(), 'short', 'short') ?></td>
and
>            <td><?= $this->i18n()->dateFormat($job->started(), 'short', 'short') ?></td>

**Comment by Daniel-KM** [comment]
Thanks, this is fixed in 3.2.11.
