### ISSUE TITLE
Problems adding extra logs

### ISSUE THREAD

**Issue by marilenadaquino** [Daniel-KM/Omeka-S-module-Log#4]
Hello I've installed your module and would like to leverage PSR to log some additional information as suggested [here](https://github.com/Daniel-KM/Omeka-S-module-Log#psr-3) 

However, after installing and configuring it, the `application.log` file keeps being empty so I'm not visualising any log in the admin dashboard tab. Second, where is exactly (in which file) that I should inject those php snippets so that it affects/prints the expected logs?

Thanks!

**Comment by pprw** [comment]
you need to change `'log' => false,` to `'log' => true,` in your config/local.config.php at least

**Comment by Daniel-KM** [comment]
Yes, it is not possible to bypass the local config of the user.
