### ISSUE TITLE
Problem installing: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes)

### ISSUE THREAD

**Issue by giorgio-ops** [Daniel-KM/Omeka-S-module-Log#5]
Hello, 

I'm trying to install the module in my Omeka S instance.

I have downloaded the last one release from this repository but, when I click on "Install" button in the admin GUI, I get the next error

`NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/nginx/html/modules/Log/src/Service/LoggerFactory.php on line 115`

I thought that problem was the PHP memory limit, so I have changed that. But error is still happening. 

Please, can you help me with this error.

**Comment by Daniel-KM** [comment]
Hi,
Do you have the full log? I cannot check the line where the issue occurs.
See https://omeka.org/s/docs/user-manual/errorLogging/

**Comment by djpresent** [comment]
Hi Daniel,

Thanks for your response. The log is 

[Tue Jul 20 17:23:39.953501 2021] [php7:error] [pid 21] [client 10.245.9.0:46882] PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/modules/Log/src/Service/LoggerFactory.php on line 80
[Tue Jul 20 17:23:53.308469 2021] [php7:error] [pid 16] [client 10.245.9.0:46980] PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/vendor/laminas/laminas-db/src/Adapter/Adapter.php on line 323
[Tue Jul 20 17:23:53.367420 2021] [php7:error] [pid 16] [client 10.245.9.0:46980] PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 262144 bytes) in /var/www/html/vendor/laminas/laminas-session/src/SessionManager.php on line 232


I have tried to install this module using apache and nginx, but the error is still happening.

**Comment by Daniel-KM** [comment]
The errors occurs during preparation of the logger, so it is related to the configuration. Have you a special config?
